code = "MZUJMKWUNUOKMKKLXOFIMOOUQKXSUVXHTNUKUUWRTSJMQGTWHXMPOXJVXCKMJTWOXJVTUKMWVHUQQKXSUVOXQQLMOWMWVZIKHHRUSMQQIYVXHTHJMKHRUKMSUMCHUORUBXHHXZUMQMJLUOVXHMQQULUKJMKXWRTSJRUWUNUORUOTDVXHHRUOUJMKKIHRTWYUPIQTMOKXSUMZXIHRTSVXHTSXNUVCOXSTWVTMWMHXTQQTWXTKJRUWMZUVTVVXHTZXIBRHMQTHHQUTSYOXNUSUWHWUMORTSPXSSMKTASTQUKCOXSVUPMHIOVXHRUOUHRUCMSXIKOMTQKJUOUKYQTHHRMHJUOUPMOOTUVOXIWVTWHRUPMSYMTBWVXHHRULJUOUPMQQUVRTKOMTQKPXSSMZIHLXIWUNUOPMWHUQQ"

decoded = []
for char, i in code
  dec = decrypted[i]
  if char in decoded
    continue
  decoded.push char
  console.log "  {from:'#{char}', to: '#{dec}'}"
